# Generated by Django 6.0 on 2026-01-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('peut_modifier_article', 'Peut modifier article'), ('peut_supprimer_article', 'Peut supprimer article')]},
        ),
    ]
